apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapi-deployment2
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge:
  selector:
    matchLabels:
      app: mywebapi2
  template:
    metadata:
      labels:
        app: mywebapi2
    spec:
      containers:
        - name: mywebapi2
          image: 147480540281.dkr.ecr.us-east-1.amazonaws.com/webapplication1:latest2
          ports:
            - containerPort: 80
          imagePullPolicy: Always
